### ISSUE TITLE
Problema misterioso

### ISSUE THREAD

**Issue by Iridion-github** [AnalistaProgrammatore/corso#1]
Iridion-github non risulta membro, seppur a lui risulti di aver accettato l'invito. Inoltre, consultare la lista membri tramite l'app mostra una lista vuota.

**Comment by nonno-cicala** [comment]
Vedo che anche a me dice _Joined at Jan 10, 2020_, probabilmente si riferisce alla creazione di AnalistaProgrammatore, dubito che tu abbia mai accettato l'invito

**Comment by Iridion-github** [comment]
Si, ci ero arrivato, visto che mi sono iscritto il 15 eheh. Conosco poco github, pensavo non avrei potuto aprire un issue senza esservi membro però.

**Comment by nonno-cicala** [comment]
L'issue è rispetto al repository, che è pubblico, non all'organizzazione.

Il lun 27 gen 2020, 06:00 Iridion-github <notifications@github.com> ha
scritto:
